import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowRight, Building2, GraduationCap, LockKeyhole, Mail } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useGetCurrentUser, useHealthCheck, useLogIn, useSignUp } from '@workspace/api-client-react';
import type { SignupInputRole } from '@workspace/api-client-react';
import { AppShell, Brand, WelcomeMark } from '@/components/campus-ui';

function AuthLayout({ children, eyebrow, title, description }: { children: ReactNode; eyebrow: string; title: string; description: string }) {
  return <AppShell><main className="paper-grid" style={{minHeight:'calc(100dvh - 72px)', display:'grid', placeItems:'center', padding:'2rem 1rem'}}><div style={{width:'min(100%, 980px)', display:'grid', gridTemplateColumns:'minmax(0, .86fr) minmax(320px, .9fr)', gap:'clamp(2rem, 8vw, 7rem)', alignItems:'center'}}><div className="reveal" style={{padding:'1rem 0'}}><WelcomeMark /><div className="eyebrow" style={{marginBottom:'.75rem'}}>{eyebrow}</div><h1 className="display" style={{fontSize:'clamp(2.7rem, 6vw, 5.1rem)', lineHeight:.95, margin:0, maxWidth:540}}>{title}</h1><p className="muted" style={{fontSize:'1.05rem', lineHeight:1.65, maxWidth:480, margin:'1.2rem 0 0'}}>{description}</p><div style={{display:'flex', gap:'.5rem', flexWrap:'wrap', marginTop:'1.8rem'}}><span className="pill pill-primary">Student-first</span><span className="pill">Real opportunities</span><span className="pill pill-coral">Human follow-through</span></div></div><div className="card reveal reveal-delay-2" style={{padding:'clamp(1.25rem, 4vw, 2rem)'}}>{children}</div></div></main></AppShell>;
}

export function LoginPage() {
  const [, setLocation] = useLocation();
  const { data: session, isLoading: sessionLoading } = useGetCurrentUser();
  const { data: health } = useHealthCheck();
  const login = useLogIn();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { if (session?.user) setLocation(session.user.role === 'company' ? '/company/dashboard' : '/jobs'); }, [session, setLocation]);
  const submit = (event: FormEvent) => { event.preventDefault(); setError(''); login.mutate({data:{email, password}}, {onSuccess:(result) => setLocation(result.user.role === 'company' ? '/company/dashboard' : '/jobs'), onError:() => setError('We could not find a match for those details.')}); };
  return <AuthLayout eyebrow="Your next chapter, closer" title="Find work that feels like a beginning." description="CampusHire brings the campus career office to your everyday. Focused roles, useful context, and a clear path from curious to hired."><form onSubmit={submit} style={{display:'grid', gap:'1rem'}}><div style={{display:'flex', justifyContent:'space-between', alignItems:'start'}}><div><h2 className="display" style={{fontSize:'1.55rem', margin:'0 0 .3rem'}}>Welcome back</h2><p className="muted" style={{fontSize:'.84rem', margin:0}}>Pick up where you left off.</p></div><span className="pill pill-primary">{health?.status === 'ok' ? 'CampusHire is live' : 'Ready when you are'}</span></div><label className="field"><span>Email</span><div style={{position:'relative'}}><Mail size={16} className="muted" style={{position:'absolute', left:'.85rem', top:'.85rem'}} /><input className="input" style={{paddingLeft:'2.4rem'}} type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@school.edu" data-testid="input-login-email" /></div></label><label className="field"><span>Password</span><div style={{position:'relative'}}><LockKeyhole size={16} className="muted" style={{position:'absolute', left:'.85rem', top:'.85rem'}} /><input className="input" style={{paddingLeft:'2.4rem'}} type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters" data-testid="input-login-password" /></div></label>{error && <p style={{color:'hsl(var(--destructive))', fontSize:'.82rem', margin:0}} data-testid="status-login-error">{error}</p>}<button className="btn btn-primary" type="submit" disabled={login.isPending || sessionLoading} data-testid="button-login">{login.isPending ? 'Signing you in…' : 'Sign in'} <ArrowRight size={16} /></button><p className="muted" style={{fontSize:'.82rem', textAlign:'center', margin:'.2rem 0 0'}}>New here? <Link href="/signup" style={{color:'hsl(var(--primary))', fontWeight:700}} data-testid="link-create-account">Create an account</Link></p></form></AuthLayout>;
}

export function SignupPage() {
  const [, setLocation] = useLocation();
  const signup = useSignUp();
  const [role, setRole] = useState<SignupInputRole>('student');
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); setError(''); signup.mutate({data:{name,email,password,role}}, {onSuccess:(result) => setLocation(result.user.role === 'company' ? '/company/dashboard' : '/jobs'), onError:() => setError('Something interrupted account creation. Check your details and try again.')}); };
  return <AuthLayout eyebrow="Start with the right room" title="A little momentum goes a long way." description="Join a focused network where students find their next yes and teams meet people before a résumé becomes a filter."><form onSubmit={submit} style={{display:'grid', gap:'1rem'}}><div><h2 className="display" style={{fontSize:'1.55rem', margin:'0 0 .3rem'}}>Create your account</h2><p className="muted" style={{fontSize:'.84rem', margin:0}}>Tell us how you’ll use CampusHire.</p></div><div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'.55rem'}}>{([{value:'student', label:'Student', icon:GraduationCap, copy:'Find your next role'}, {value:'company', label:'Company', icon:Building2, copy:'Meet emerging talent'}] as const).map((item) => { const Icon = item.icon; return <button type="button" key={item.value} onClick={() => setRole(item.value)} className={`card ${role === item.value ? 'selected-role' : ''}`} style={{padding:'.85rem', textAlign:'left', borderColor:role === item.value ? 'hsl(var(--primary))' : undefined, background:role === item.value ? 'color-mix(in srgb, hsl(var(--primary)) 8%, hsl(var(--card)))' : undefined}} data-testid={`button-role-${item.value}`}><Icon size={19} style={{color:'hsl(var(--primary))'}} /><strong style={{display:'block', marginTop:'.55rem', fontSize:'.87rem'}}>{item.label}</strong><span className="muted" style={{fontSize:'.71rem'}}>{item.copy}</span></button>; })}</div><label className="field"><span>{role === 'company' ? 'Company name' : 'Your name'}</span><input className="input" required value={name} onChange={(e) => setName(e.target.value)} placeholder={role === 'company' ? 'Northstar Labs' : 'Jordan Lee'} data-testid="input-signup-name" /></label><label className="field"><span>Email</span><input className="input" required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@school.edu" data-testid="input-signup-email" /></label><label className="field"><span>Password</span><input className="input" required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters" data-testid="input-signup-password" /></label>{error && <p style={{color:'hsl(var(--destructive))', fontSize:'.82rem', margin:0}} data-testid="status-signup-error">{error}</p>}<button className="btn btn-primary" type="submit" disabled={signup.isPending} data-testid="button-signup">{signup.isPending ? 'Setting things up…' : 'Create account'} <ArrowRight size={16} /></button><p className="muted" style={{fontSize:'.82rem', textAlign:'center', margin:'.2rem 0 0'}}>Already have an account? <Link href="/" style={{color:'hsl(var(--primary))', fontWeight:700}} data-testid="link-signin">Sign in</Link></p></form></AuthLayout>;
}