import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Check, ChevronDown, ClipboardList, Eye, Plus, Send, Users, X } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetCompanyDashboardQueryKey, getListJobApplicantsQueryKey, useCreateJob, useGetCompanyDashboard, useListJobApplicants, useUpdateApplicationStatus } from '@workspace/api-client-react';
import type { Application, Job, User } from '@workspace/api-client-react';
import { AppShell, EmptyState, ErrorState, LoadingList, PageTitle, StatusPill } from '@/components/campus-ui';

export function CompanyDashboardPage({ user, onLogout }: { user: User; onLogout: () => void }) {
  const queryClient = useQueryClient();
  const dashboardQuery = useGetCompanyDashboard();
  const createJob = useCreateJob();
  const [showJobForm, setShowJobForm] = useState(false);
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [notice, setNotice] = useState('');
  const dashboard = dashboardQuery.data;
  const publish = (data: {title:string;description:string;requirements:string[];location:string;type:string;salary?:string}) => createJob.mutate({data}, {onSuccess:() => { setShowJobForm(false); setNotice('Your role is live. Applicants can see it now.'); queryClient.invalidateQueries({queryKey:getGetCompanyDashboardQueryKey()}); }, onError:() => setNotice('We could not publish that role yet.')});
  return <AppShell user={user} onLogout={onLogout}><main className="page-wrap"><PageTitle eyebrow="Recruiter workspace" title="Build the next great class." description="A clear view of your roles, your reach, and the students who have raised their hands." action={<button className="btn btn-primary" onClick={() => setShowJobForm(true)} data-testid="button-open-job-form"><Plus size={16} /> Post a role</button>} />{notice && <div className="toast-note" data-testid="status-company-notice"><Check size={15} style={{verticalAlign:'middle', marginRight:'.35rem', color:'hsl(var(--primary))'}} />{notice}<button className="icon-btn" style={{display:'inline-grid', marginLeft:'.7rem', width:25, height:25}} onClick={() => setNotice('')} data-testid="button-dismiss-company-notice">×</button></div>}{dashboardQuery.isLoading ? <LoadingList count={3} /> : dashboardQuery.isError ? <ErrorState message="The recruiting overview could not be loaded." onRetry={() => dashboardQuery.refetch()} /> : <><div style={{display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))', gap:'.8rem', marginBottom:'1.5rem'}}><Metric label="Total applicants" value={dashboard?.totalApplicants ?? 0} icon={Users} tone="primary" /><Metric label="Interviews" value={dashboard?.interviews ?? 0} icon={ClipboardList} tone="coral" /><Metric label="Profile views" value={dashboard?.profileViews ?? 0} icon={Eye} tone="sand" /></div><section className="card" style={{overflow:'hidden'}}><div style={{padding:'1.15rem 1.3rem', display:'flex', alignItems:'center', justifyContent:'space-between', gap:'.7rem', borderBottom:'1px solid hsl(var(--border))'}}><div><div className="eyebrow">Your open roles</div><h2 className="display" style={{fontSize:'1.5rem', margin:'.25rem 0 0'}}>Roles with a pulse</h2></div><span className="pill">{dashboard?.jobs.length ?? 0} live</span></div>{dashboard?.jobs.length ? dashboard.jobs.map((job) => <JobRow key={job.id} job={job} onSelect={() => setSelectedJob(job)} />) : <EmptyState icon="briefcase" title="Your first role sets the tone." description="Give students enough context to picture themselves on the team." action={<button className="btn btn-primary" onClick={() => setShowJobForm(true)} data-testid="button-empty-post">Post your first role</button>} />}</section></>}{showJobForm && <JobForm onClose={() => setShowJobForm(false)} onSubmit={publish} pending={createJob.isPending} />}{selectedJob && <ApplicantDrawer job={selectedJob} onClose={() => setSelectedJob(null)} onNotice={setNotice} />}</main></AppShell>;
}

function Metric({label,value,icon:Icon,tone}:{label:string;value:number;icon:typeof Users;tone:'primary'|'coral'|'sand'}) {
  const colors = {primary:'hsl(var(--primary))',coral:'hsl(var(--accent))',sand:'hsl(34 54% 47%)'};
  return <div className="card" style={{padding:'1rem', display:'flex', gap:'.8rem', alignItems:'center'}} data-testid={`metric-${label.replaceAll(' ','-')}`}><div style={{width:38,height:38,display:'grid',placeItems:'center',borderRadius:12,color:colors[tone],background:'hsl(var(--secondary))'}}><Icon size={18} /></div><div><div className="display" style={{fontSize:'1.6rem', lineHeight:1}}>{value}</div><div className="muted" style={{fontSize:'.74rem', marginTop:'.3rem'}}>{label}</div></div></div>;
}

function JobRow({job,onSelect}:{job:Job;onSelect:()=>void}) {
  return <button onClick={onSelect} style={{width:'100%', display:'flex', alignItems:'center', justifyContent:'space-between', gap:'1rem', padding:'1.1rem 1.3rem', border:0, borderBottom:'1px solid hsl(var(--border))', textAlign:'left', color:'inherit', background:'transparent', transition:'background .2s'}} data-testid={`button-job-row-${job.id}`}><span style={{display:'flex', alignItems:'center', gap:'.8rem'}}><span className="avatar" style={{borderRadius:12, background:'hsl(var(--secondary))', color:'hsl(var(--primary))'}}>{job.companyInitials}</span><span><strong style={{display:'block', fontSize:'.92rem'}}>{job.title}</strong><span className="muted" style={{fontSize:'.78rem'}}>{job.location} · {job.applicantsCount} applicants</span></span></span><span style={{display:'flex', alignItems:'center', gap:'.6rem'}}><span className="pill pill-primary">Review applicants</span><ArrowUpRight size={16} className="muted" /></span></button>;
}

function JobForm({onClose,onSubmit,pending}:{onClose:()=>void;onSubmit:(data:{title:string;description:string;requirements:string[];location:string;type:string;salary?:string})=>void;pending:boolean}) {
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [requirements,setRequirements]=useState(''); const [location,setLocation]=useState(''); const [type,setType]=useState('Internship'); const [salary,setSalary]=useState('');
  const submit=(e:FormEvent)=>{e.preventDefault();onSubmit({title,description,requirements:requirements.split('\n').map((item)=>item.trim()).filter(Boolean),location,type,salary:salary||undefined});};
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><div className="eyebrow">Make the invitation clear</div><h2 className="display" style={{fontSize:'1.6rem',margin:'.3rem 0 0'}}>Post a new role</h2></div><button className="icon-btn" onClick={onClose} data-testid="button-close-job-form"><X size={17}/></button></div><form className="modal-body" onSubmit={submit} style={{display:'grid',gap:'1rem'}}><label className="field"><span>Role title</span><input className="input" required value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Marketing intern" data-testid="input-job-title" /></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'.7rem'}}><label className="field"><span>Location</span><input className="input" required value={location} onChange={(e)=>setLocation(e.target.value)} placeholder="Chicago, IL / Remote" data-testid="input-job-form-location" /></label><label className="field"><span>Type</span><select className="select" value={type} onChange={(e)=>setType(e.target.value)} data-testid="select-job-form-type"><option>Internship</option><option>Full-time</option><option>Part-time</option></select></label></div><label className="field"><span>Salary or range <small className="muted">(optional)</small></span><input className="input" value={salary} onChange={(e)=>setSalary(e.target.value)} placeholder="$22–28 / hour" data-testid="input-job-salary" /></label><label className="field"><span>Description</span><textarea className="textarea" required value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Help students picture the work, team, and first 90 days." data-testid="input-job-description" /></label><label className="field"><span>Requirements <small className="muted">(one per line)</small></span><textarea className="textarea" required value={requirements} onChange={(e)=>setRequirements(e.target.value)} placeholder="Curiosity and clear communication&#10;Comfort learning in public" data-testid="input-job-requirements" /></label><div style={{display:'flex',justifyContent:'flex-end',gap:'.55rem'}}><button type="button" className="btn btn-ghost" onClick={onClose} data-testid="button-cancel-job">Cancel</button><button type="submit" className="btn btn-primary" disabled={pending} data-testid="button-publish-job"><Send size={15}/>{pending?'Publishing…':'Publish role'}</button></div></form></section></div>;
}

function ApplicantDrawer({job,onClose,onNotice}:{job:Job;onClose:()=>void;onNotice:(message:string)=>void}) {
  const queryClient=useQueryClient(); const applicantsQuery=useListJobApplicants(job.id,{query:{queryKey:getListJobApplicantsQueryKey(job.id)}}); const update=useUpdateApplicationStatus();
  const changeStatus=(application:Application,status:Application['status'])=>update.mutate({applicationId:application.id,data:{status}}, {onSuccess:()=>{onNotice(`Updated ${application.studentName} to ${status}.`);queryClient.invalidateQueries({queryKey:getListJobApplicantsQueryKey(job.id)});},onError:()=>onNotice('We could not update that applicant yet.')});
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose();}}><section className="modal" role="dialog" aria-modal="true" style={{width:'min(720px,100%)'}}><div className="modal-head"><div><div className="eyebrow">Applicant review</div><h2 className="display" style={{fontSize:'1.55rem',margin:'.3rem 0 .2rem'}}>{job.title}</h2><p className="muted" style={{margin:0,fontSize:'.8rem'}}>A thoughtful response starts with a thoughtful look.</p></div><button className="icon-btn" onClick={onClose} data-testid="button-close-applicants"><X size={17}/></button></div><div className="modal-body">{applicantsQuery.isLoading?<LoadingList count={2}/>:applicantsQuery.isError?<ErrorState message="Applicant details could not be loaded." onRetry={()=>applicantsQuery.refetch()}/>:!applicantsQuery.data?.length?<EmptyState icon="file" title="No applications yet." description="Your role is live. The right person may be reading it right now."/>:<div style={{display:'grid',gap:'.7rem'}}>{applicantsQuery.data.map((applicant)=><ApplicantRow key={applicant.id} applicant={applicant} onChange={changeStatus}/>)}</div>}</div></section></div>;
}

function ApplicantRow({applicant,onChange}:{applicant:Application;onChange:(application:Application,status:Application['status'])=>void}) {
  const [open,setOpen]=useState(false);
  return <div className="card" style={{padding:'1rem',boxShadow:'none'}} data-testid={`row-applicant-${applicant.id}`}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'.8rem',flexWrap:'wrap'}}><div style={{display:'flex',alignItems:'center',gap:'.7rem'}}><div className="avatar">{applicant.studentName.slice(0,2).toUpperCase()}</div><div><strong style={{display:'block'}}>{applicant.studentName}</strong><span className="muted" style={{fontSize:'.77rem'}}>{applicant.studentEmail}</span></div></div><div style={{display:'flex',alignItems:'center',gap:'.55rem'}}><StatusPill status={applicant.status}/><button className="icon-btn" onClick={()=>setOpen(!open)} aria-label="Change applicant status" data-testid={`button-status-menu-${applicant.id}`}><ChevronDown size={16}/></button></div></div>{open&&<div style={{display:'flex',gap:'.45rem',flexWrap:'wrap',marginTop:'.85rem',paddingTop:'.8rem',borderTop:'1px solid hsl(var(--border))'}}>{(['reviewed','interview','rejected'] as const).map((status)=><button key={status} className={`btn ${status==='interview'?'btn-coral':'btn-ghost'}`} onClick={()=>{onChange(applicant,status);setOpen(false);}} data-testid={`button-set-status-${status}-${applicant.id}`}>{status==='interview'?'Invite to interview':status==='rejected'?'Close application':'Mark reviewed'}</button>)}{applicant.resumeUrl&&<a className="btn btn-secondary" href={applicant.resumeUrl} target="_blank" rel="noreferrer" data-testid={`link-resume-${applicant.id}`}>View resume</a>}</div>}</div>;
}